"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import Header from "@/components/Header";
import { Providers } from "@/redux/provider";
import CheckAuth from "@/components/CheckAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          <CheckAuth>
            {pathname !== "/" ? <Header /> : null}
            <>{children}</>
          </CheckAuth>
        </Providers>
      </body>
    </html>
  );
}
